### PR TITLE
Android small window mode soft keyboard black occlusion

### PR DESCRIPTION
**Pull request by Zuoqiu-Yingyi**
REF: https://github.com/siyuan-note/siyuan/issues/9726

### CODE REVIEW

**Comment by 88250** [comment]
发现个小问题，我这里小米 12 上面点输入法的隐藏按钮会有问题：


https://github.com/siyuan-note/siyuan-android/assets/873584/ecbfbcf3-4fc2-42a9-9d76-4de05b6fe7c1

**Comment by Zuoqiu-Yingyi** [comment]
这里应该是前端的问题，收缩软键盘后再显示光标时，若光标位置与之前一样，就不显示编辑工具栏了

**Comment by 88250** [comment]
好的，那等会我和 @Vanessa219 看下。

**Comment by 88250** [comment]
关联 https://github.com/siyuan-note/siyuan/issues/9765

**Pull request merged**
